### PR TITLE
Add a test for Thread::Pool

### PR DESCRIPTION
**Pull request by nownabe**
This is a test for #34 

This test pass with v0.1.7. and does not pass with v0.1.6.

### CODE REVIEW

**Comment by meh** [comment]
Thanks, but closing this, I already wrote specs that didn't pass on 0.1.6, and much more.

**Comment by nownabe** [comment]
Thanks for your review.
Sorry, I missed your specs.
Can you tell me which specs are for this?

**Comment by meh** [comment]
@nownabe just pushed them, the `#done?` and `#idle?` specs would fail on 0.1.6.

**Comment by nownabe** [comment]
@meh I got it! Thanks!

**Pull request closed without merging**
